/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/model/spaceship/scene.gltf 
Author: markkingsnorth (https://sketchfab.com/markkingsnorth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aeon-dart-iv-d8f60129cb954f7ebf57fd234e6e2524
Title: Aeon Dart IV
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('model/spaceship/scene.gltf')
  //add lighting
 
  return (
    <group {...props} dispose={null}>
        
      

      <mesh geometry={nodes.Object_4.geometry} material={materials.Space_Jet_Atlas} position={[2.351, 1.59, 0.005]} rotation={[1.656, 1.473, -1.646]} scale={0.585} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Inner_Grille} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Canopy} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Boosters} />
    </group>
  )
}

useGLTF.preload('model/spaceship/scene.gltf')
