/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/model/tesla/scene.gltf 
Author: treechai111 (https://sketchfab.com/treechai111)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/tesla-roadster-20-439a7e7f228f4d3281998aa9985e98e1
Title: Tesla Roadster 2.0
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Tesla(props) {
  const { nodes, materials } = useGLTF("model/tesla/scene.gltf");
  for (const material of Object.values(materials)) {
    //to give the tesla model a shine
    if (material.emissive) {
      material.emissive = material.color;
      material.emissiveIntensity = 0.3;
    }
  }

  const ref = useRef();
  const initialX = -1;
  const initialY = -1;
  const radius = 3;
  let angle = 0;
  useFrame((state, delta) => {
    const x = initialX + radius * Math.cos(0.6*angle);
    const y = initialY + radius * Math.sin(0.4*angle);

    ref.current.position.x = x;
    ref.current.position.y = y;

    ref.current.position.z = Math.cos( 0.4 * state.clock.getElapsedTime() * 0.9); 

    angle += 0.007;
  });

  return (
    <group
      ref={ref}
      {...props}
      dispose={null}
      rotation={[Math.PI / 8, Math.PI / 6, -Math.PI / 4]}
    >
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Glass_Material015_0.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            geometry={nodes.Glass_Material_0.geometry}
            material={materials.Material}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Black_Body_Material002_0.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Black_Body_Material002_0_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Headlight_Material005_0.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Headlight_Material002_0.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Headlight_Material004_0.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            geometry={nodes.Headlight_Material006_0.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.side_Light_Material012_0.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.side_Light_Material003_0.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            geometry={nodes.side_Light_Material016_0.geometry}
            material={materials["Material.016"]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Breaks_Material010_0.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            geometry={nodes.Breaks_Material013_0.geometry}
            material={materials["Material.013"]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Tires_Material008_0.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Tires_Material008_0_1.geometry}
            material={materials["Material.008"]}
          />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Disc_Material011_0.geometry}
            material={materials["Material.011"]}
          />
          <mesh
            geometry={nodes.Disc_Material009_0.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Disc_Material007_0.geometry}
            material={materials["Material.007"]}
          />
        </group>
        <mesh
          geometry={nodes.Body_base_Material002_0.geometry}
          material={materials["Material.002"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Logo_Material013_0.geometry}
          material={materials["Material.013"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Maxs_Material007_0.geometry}
          material={materials["Material.007"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Body_Material001_0.geometry}
          material={materials["Material.001"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("model/tesla/scene.gltf");
