import { Inter } from "next/font/google";
import "./globals.css";
import Experience from "@/app/components/Experience";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen">
          <Experience>{children}</Experience>
        </div>
      </body>
    </html>
  );
}
